language: cpp
compiler:
    - make
os:
    - linux

env:
    - PROJECT=quinto.pro
    - PROJECT=tests.pro

before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -qq qt5-qmake qtbase5-dev qttools5-dev-tools qtdeclarative5-dev
    - sudo apt-get install -qq libboost-dev

script:
    - qmake -qt=qt5 -spec linux-g++ $PROJECT
    - make --always-make -f Makefile all
