notifications:
    email: false
  
language: cpp
compiler:
    - make
os:
    - linux

env:
    - PROJECT=quinto.pro
    - PROJECT=tests.pro

before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -qq qt5-qmake qtbase5-dev qttools5-dev-tools qtdeclarative5-dev
    - sudo apt-get install -qq libboost-dev
    - gem install coveralls-lcov
    - svn export https://github.com/mrzechonek/tut-framework/trunk/include $HOME/lib/tut/include
    - svn export https://github.com/linux-test-project/lcov/tags/v1.12 $HOME/gcovinstaller
    - sudo make -C $HOME/gcovinstaller install

script:
    - qmake -qt=qt5 -spec linux-g++ $PROJECT
    - make --always-make -f Makefile all
