language: cpp
compiler:
    - make
os:
    - linux

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install qtbase5-dev
    - sudo apt-get install qt5-default qttools5-dev-tools
    - sudo apt-get install libboost-ublas-dev

script:
    - qmake -spec linux-g++ quinto.pro
    - make --always-make -f Makefile all
